TARGET = init
OBJECTS = base.o init.o

DEPEND_LIB = ${PROJECT_PATH}/src/base/log.o ${PROJECT_PATH}/src/base/system_properties.o ${PROJECT_PATH}/src/base/util.o

all: ${OBJECTS} ${TARGET}

include ${MAKE_INCLUDE}

